slime/slime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('behavior/', include('slime_behavior.urls'))
]

slime/slime_behavior/urls.py
from django.urls import path

from . import views

app_name = 'slime_behavior'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<str:slime_name>/action', views.slime_action, name='action'),
	path('details/<int:pk>', views.DetailsView.as_view(), name='slime_details'),
	path('<str:slime_name>/action_change', views.action_change, name='action_change'),
	path('<str:slime_name>', views.slime, name='slime'),
]

slime/slime_behavior/models.py
from django.db import models
from datetime import datetime


class Action(models.Model):
	action_name = models.CharField(max_length=70)
	pub_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.action_name


class SlimeTypes(models.Model):
	type_index = models.IntegerField(primary_key=True)
	description = models.CharField(max_length=50)

	def __str__(self):
		return self.description


class Slime(models.Model):
	action = models.ForeignKey("Action", on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	type = models.ForeignKey("SlimeTypes", on_delete=models.CASCADE, to_field='type_index')

	
	color = models.TextField(default='No color')

	def set_color(self):
		if self.type.description == 'pyro':
			self.color = 'orange'
		elif self.type.description == 'hydro':
			self.color = 'blue'
		else:
			self.color = 'green'
		self.save()
	
	def __str__(self):
		return self.name

	def change_action(self, new_action):
		if self.action.action_name != new_action:
			action, _ = Action.objects.get_or_create(action_name=new_action, defaults={'pub_date': datetime.now()})
			self.action = action
			self.save()
			print('Ok lets do this >_<')
		else:
			print('I am doing it!! -_-')

slime/slime_behavior/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
#from django.template import loader
from django.urls import reverse
from .models import Slime, Action, SlimeTypes
from django.views import generic
from django.db.models import Q

class IndexView(generic.ListView):
    template_name = 'slime_behavior/index.html'
    context_object_name = 'all_slimes'

    def get_queryset(self):
        """Return all slimes."""
        return Slime.objects.filter(~Q(color='No color')).order_by('-name')[:]


class DetailsView(generic.DetailView):
	model = Slime
	template_name = 'slime_behavior/details.html'

	def get_queryset(self):
		"""Return all slimes."""
		return Slime.objects.filter(~Q(color='No color'))


def slime_action(request, slime_name):
	slime = get_object_or_404(Slime, name=slime_name)
	try:
		selected_action = Action.objects.get(id=request.POST['action_id'])

	except (KeyError, Action.DoesNotExist):
		return render(request,'slime_behavior/slime.html', {'slime': slime,
															'all_actions':Action.objects.order_by('-action_name')[:] , 
										'error_message': f"Select something, stupid human!! *@%$& {request.POST}"})
	else:
		if slime.action.action_name == selected_action.action_name:
			return render(request,'slime_behavior/action_change.html',{'slime': slime, 
															'all_actions': Action.objects.order_by('-action_name')[:]})
		else:
			return HttpResponseRedirect(reverse('slime_behavior:index'))
			#HttpResponse('Nope, stupid human!!><')


def action_change(request, slime_name):
	slime = get_object_or_404(Slime, name=slime_name)
	try:
		slime.action = Action.objects.get(id=request.POST['action_id'])
		slime.save()

	except (KeyError, Action.DoesNotExist):
		return render(request,'slime_behavior/action_change.html', {'slime': slime,
															'all_actions':Action.objects.order_by('-action_name')[:] , 
										'error_message': f"Select something, stupid human!! *@%$& {request.POST}"})
	else:
		return render(request,'slime_behavior/action_changed.html')


def slime(request, slime_name):
	try:
		slime = Slime.objects.get(name=slime_name)
		all_actions = Action.objects.order_by('-action_name')[:]
		return render(request, 'slime_behavior/slime.html', {'slime': slime, 'all_actions': all_actions})
	except Slime.DoesNotExist:
		raise Http404(f'Slime {slime_name} is drunk as fuck. Try to call later')



##TODO: Use the template system
def slime_by_id(request, slime_id):
#	#slime_type = 'pyro'
	#slime = Slime.objects.get(id=2)
	slime_type = Slime.objects.get(id=slime_id).type
	slime_name = Slime.objects.get(id=slime_id).name
	return HttpResponse(f'My name is {slime_name}. I am a {slime_type} slime!')
	#return HttpResponse(slime)


# Create your views here.

slime/slime_behavior/templates/slime_behavior/action_change.html
<h2>Yes, I am {{slime.action}}ing!</h2>
<h3> Lets change my action! (If you don`t wanxt changes, just choose same action)</h3>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'slime_behavior:action_change' slime.name %}" method="post">
{% csrf_token %}
{% for action in all_actions %}
    <input type="radio" name="action_id" id="choice{{ forloop.counter }}" value="{{ action.id }}">
    <label for="choice{{ forloop.counter }}">{{ action.action_name }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

slime/slime_behavior/templates/slime_behavior/action_changed.html
<p>Action changed</p>
<form action="{% url 'slime_behavior:index' %}" method="get">
{% csrf_token %}
<input type="submit" value="Back">
</form>

slime/slime_behavior/templates/slime_behavior/details.html
<h3>Slime: {{slime.name}} </h3>
<h3>Type: {{slime.type}} </h3>
<h3>Action: {{slime.action}} </h3>
<h3>Color: {{slime.color}} </h3>

slime/slime_behavior/templates/slime_behavior/index.html
<!-- хуярить к списку слаймов опцию 2 форм - екшены и детали-->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'slime_behavior/style.css'%}">
{% if all_slimes %}
<h2>Hi, slimes!</h2>
    <ul>
    {% for slime_ in all_slimes %}
        <li>{{slime_.name}}  <a href="{% url 'slime_behavior:slime_details' slime_.id %}">Details</a>        
        	<a href="{% url 'slime_behavior:slime' slime_.name %}">Action</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No slimes are available.</p>
{% endif %}

slime/slime_behavior/templates/slime_behavior/slime.html
<h2>My name is {{slime.name}}. I am a(n) {{slime.type}} slime!</h2>
<h3> Try to guess, what I am doing?</h3>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'slime_behavior:action' slime.name %}" method="post">
{% csrf_token %}
{% for action in all_actions %}
    <input type="radio" name="action_id" id="choice{{ forloop.counter }}" value="{{ action.id }}">
    <label for="choice{{ forloop.counter }}">{{ action.action_name }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>